# Generated by Django 5.0.1 on 2024-03-18 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(default='', max_length=50)),
                ('celular', models.CharField(default='', max_length=30)),
                ('endereco', models.TextField(null=True)),
                ('cpf', models.CharField(default='', max_length=30, unique=True)),
                ('rg', models.CharField(default='', max_length=50)),
                ('email', models.CharField(max_length=100, null=True)),
                ('ano', models.IntegerField(default=0)),
                ('turma', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plano_Ensino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_ensino', models.FileField(default=None, upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('local', models.FileField(default=None, upload_to='pdfs/')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(default='', max_length=50)),
                ('celular', models.CharField(default='', max_length=30)),
                ('endereco', models.TextField(null=True)),
                ('cpf', models.CharField(default='', max_length=30, unique='True')),
                ('rg', models.CharField(default='', max_length=50)),
                ('email', models.CharField(max_length=100, null=True)),
                ('ano', models.IntegerField(default=0)),
                ('disciplina', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='siteapp.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(default='', max_length=100)),
                ('descricao', models.TextField(null=True)),
                ('professor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='siteapp.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno_tem_professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno_tem_disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(default='2023', max_length=4)),
                ('status', models.CharField(default='Cursando', max_length=10)),
                ('nota', models.FloatField(default=0.0, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.disciplina')),
            ],
            options={
                'unique_together': {('aluno', 'disciplina', 'ano')},
            },
        ),
    ]
