# Generated by Django 5.0.1 on 2024-03-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_alter_aluno_email_alter_aluno_rg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.CharField(max_length=100, null=True, unique='True'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='rg',
            field=models.CharField(default='', max_length=50, unique='True'),
        ),
    ]
