# Generated by Django 5.0.1 on 2024-03-19 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_alter_professor_email_alter_professor_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='disciplina',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='siteapp.disciplina'),
        ),
    ]
