# Generated by Django 5.0.1 on 2024-03-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0006_aluno_perfil_professor_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='status_cadastro',
            field=models.CharField(default='Inativo', max_length=100),
        ),
    ]
