# Generated by Django 5.0.1 on 2024-03-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0007_professor_status_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='status_cadastro',
            field=models.CharField(default='Ativo', max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='status_cadastro',
            field=models.CharField(default='Ativo', max_length=100),
        ),
    ]
